#!/bin/bash
# Get the C file name from the environment variable
CFILE=$CFILE
# Extract the file name without extension
BASENAME=$(basename $CFILE .c)
# Compile the C file without linking
gcc -c $CFILE -o $BASENAME.o
